#pragma once
#include "CoreMinimal.h"
#include "EEndFootAttributeTypes.generated.h"

UENUM()
enum class EEndFootAttributeTypes : int32 {
    None,
    Metal_Parts,
    Metal_Floor,
    Metal_Ami,
    Con_Clean,
    Con_Sandmix,
    Con_Water,
    Wood_Floor,
    Wood_Parts,
    Wood_Old,
    Soil,
    Stone,
    Gravel,
    Grass,
    Carpet,
    Glass,
    Sand,
    Crap_Con,
    Crap_Pla,
    Crap_Tra,
    Woodchip,
    Water_Default,
    Water_Swamp,
    Rubber,
    Metal_Totan,
    Metal_Cavity,
    Metal_Frame,
    Wood_Piller,
    Tarp,
    Slimy,
    Water_River,
    Water_Ocean,
    Water_SandSwamp,
    Water_Default_Shallow,
    Water_Swamp_Shallow,
    Water_River_Shallow,
    Water_Ocean_Shallow,
    Water_SandSwamp_Shallow,
    MAX,
};

