#pragma once
#include "CoreMinimal.h"
#include "EEndLoadLevelPriority.generated.h"

UENUM(BlueprintType)
enum class EEndLoadLevelPriority : uint8 {
    STREAM_LEVEL_NONE,
    STREAM_LEVEL_BACK_GROUND = 64,
    STREAM_LEVEL_DEFAULT_PRIORITY = 128,
    STREAM_LEVEL_LEVELSEQUENCELOADER_ANIMATION_PRIORITY = 160,
    STREAM_LEVEL_CHARA_POP_LOAD_PRIORITY = STREAM_LEVEL_LEVELSEQUENCELOADER_ANIMATION_PRIORITY,
    STREAM_LEVEL_CHARA_POP_UNLOAD_PRIORITY,
    STREAM_LEVEL_ENVSET_PRIORITY = 170,
    STREAM_LEVEL_ABILITY_PRIORITY = 180,
    STREAM_LEVEL_MENU_PRIORITY = 190,
    STREAM_LEVEL_LOCATION_ENTRY_PRIORITY = 195,
    STREAM_LEVEL_FIRST_CINEMA_PRIORITY = 200,
    STREAM_LEVEL_PLANER_CINEMA_PRIORITY = 210,
    STREAM_LEVEL_PARTY_CHARACTER_PRIORITY = 230,
    STREAM_LEVEL_SECONDRY_CINEMA_PRIORITY = 253,
    STREAM_LEVEL_INCREMENT_REFERENCE_COUNTER,
    STREAM_LEVEL_UNLOAD,
};

