#pragma once
#include "CoreMinimal.h"
#include "EEndForceFeedbackEffect.generated.h"

UENUM(BlueprintType)
enum class EEndForceFeedbackEffect : uint8 {
    FFB_Effect0,
    FFB_Effect1,
    FFB_Effect2,
    FFB_Effect3,
    FFB_Effect4,
    FFB_Effect5,
    FFB_Effect6,
    FFB_Effect7,
    FFB_Effect8,
    FFB_Effect9,
    FFB_Noise1,
    FFB_FACT0,
    FFB_FACT1,
    FFB_FACT2,
    FFB_FACT3,
    FFB_FACT4,
    FFB_FACT5,
    FFB_FACT6,
    FFB_FACT7,
    FFB_FACT8,
    FFB_FACT9,
    FFB_Bike0,
    FFB_Bike1,
    FFB_Bike2,
    FFB_FACT10,
    FFB_FACT11,
    FFB_Minigame0,
    FFB_Minigame1,
    FFB_Minigame2,
    FFB_Minigame3,
    FFB_Minigame4,
    FFB_Minigame5,
    FFB_Minigame6,
    FFB_Minigame7,
    FFB_Minigame8,
    FFB_Minigame9,
    FFB_Minigame10,
    FFB_Minigame11,
    FFB_CutScene00,
    FFB_CutScene01,
    FFB_CutScene02,
    FFB_CutScene03,
    FFB_CutScene04,
    FFB_CutScene05,
    FFB_CutScene06,
    FFB_CutScene07,
    FFB_CutScene08,
    FFB_CutScene09,
    FFB_CutScene10,
    FFB_CutScene11,
    FFB_CutScene12,
    FFB_CutScene13,
    FFB_CutScene14,
    FFB_CutScene15,
    FFB_CutScene16,
    FFB_CutScene17,
    FFB_CutScene18,
    FFB_CutScene19,
};

