#pragma once
#include "CoreMinimal.h"
#include "EShootingSEType.generated.h"

UENUM()
enum class EShootingSEType : int32 {
    HitMastCloth,
    HitSingleShot,
    HitWater,
    HitWoodenObjects,
    HitCarpet,
    HitStone,
    HitSlimy,
    InsertBigWave,
    InsertSmallWave,
    KillRareTargetSingleShot,
    KillSingleShot,
    Shot,
    PhaseTelop,
    KillFlipTargetShot,
    StartCount,
    Start,
    EndCount,
    TimeOver,
    Result,
    Result_off,
    KillSp_Stamp,
    KillSp_Moogle,
    KillSp_DebuChocobo,
    KillSp_Morbol,
    KillSp_Sabotender,
    ResultScore_On,
    ResultScore_Off,
    Create_Sabotender,
    HitRate_OVER,
    HitRate_UNDER,
    HitScore_EXCELLENT,
    HitScore_GREAT,
    HitScore_NICE,
    HitScore_GOOD,
    GetReady,
    Option_Control,
    Option_Weight,
    Option_Motion,
    HighScore_Loop,
    HighScore_Cheers,
    Max,
    None,
};

