#pragma once
#include "CoreMinimal.h"
#include "ESummonPointUsageFlag.generated.h"

UENUM(BlueprintType)
enum class ESummonPointUsageFlag : uint8 {
    eSpawn_All,
    eSpawn_Ifrit,
    eSpawn_Chocobo,
    eSpawn_Shiva,
    eSpawn_Leviathan,
    eSpawn_Bahamut,
    eSpawn_DebuChoco,
    eSpawn_Carbuncle,
    eSpawn_Cactuar,
    eSpawn_Hinachocobo,
    eSpawn_Ramuh,
    eSpawn_Titan,
    eSpawn_Odin,
    eSpawn_Kjata,
    eSpawn_Alexander,
    eSpawn_Phoenix,
    eSpawn_NeoBahamut,
    eSpawn_Gilgamesh,
    eSpawn_Magicpot,
    eSpawn_End2Hinachocobo,
    eSpawn_DLCMoogle,
    eWarp_All,
    eWarp_Ifrit,
    eWarp_Chocobo,
    eWarp_Shiva,
    eWarp_Leviathan,
    eWarp_Bahamut,
    eWarp_DebuChoco,
    eWarp_Carbuncle,
    eWarp_Cactuar,
    eWarp_Hinachocobo,
    eWarp_Ramuh,
    eWarp_Titan,
    eWarp_Odin,
    eWarp_Kjata,
    eWarp_Alexander,
    eWarp_Phoenix,
    eWarp_NeoBahamut,
    eWarp_Gilgamesh,
    eWarp_Magicpot,
    eWarp_End2Hinachocobo,
    eWarp_DLCMoogle,
    eOmen,
    eCutScene,
    eResetLocation,
    eLevelCutScene,
    eMax,
};

