#include "EndDataObjectLifeSpotInputMiniGameLocationParameterAccessor.h"

FEndDataObjectLifeSpotInputMiniGameLocationParameterAccessor::FEndDataObjectLifeSpotInputMiniGameLocationParameterAccessor() {
}

