#include "EndDataObjectJunonParadeTownSoldierFormationMatchingAccessor.h"

FEndDataObjectJunonParadeTownSoldierFormationMatchingAccessor::FEndDataObjectJunonParadeTownSoldierFormationMatchingAccessor() {
}

