#pragma once
#include "CoreMinimal.h"
#include "EEndSkillEffectType.generated.h"

UENUM(BlueprintType)
enum class EEndSkillEffectType : uint8 {
    None,
    HPMaxAdd,
    MPMaxAdd,
    PhysicsAttackAdd,
    PhysicsDefenseAdd,
    MagicAttackAdd,
    MagicDefenseAdd,
    CriticalRateAdd,
    LuckAdd,
    DexterityAdd,
    LimitLevelBaseAdd,
    GiveDamageCriticalAdd = 20,
    GiveDamageFireAdd,
    GiveDamageIceAdd,
    GiveDamageThunderAdd,
    GiveDamageWindAdd,
    GiveDamageWeaponAbilityAdd,
    GiveDamageLimitAbilityAdd,
    GiveDamageGroundNormalAttackComboAdd,
    GiveDamageAerialNormalAttackComboAdd,
    GiveDamageStateBurstAdd,
    GiveDamageWeakAttributeAdd,
    GiveDamageAttributeAdd,
    GiveDamageLimitOver,
    GiveDamageUniqueAbilityAdd,
    GiveDamageNormalAttackAdd,
    GiveDamageAerialAttackAdd,
    GiveDamageBreakablePartAdd,
    GiveDamageBackAdd,
    GiveDamageMPFullMPSpendAdd,
    GiveDamageSelfHPRecoverAdd,
    GiveDamageHPRecoverAdd,
    GiveDamageAddTakeDamageAdd,
    GiveDamageSubTakeDamageSub,
    GiveDamageAbilityAdd,
    TakeDamageFireSub = 50,
    TakeDamageIceSub,
    TakeDamageThunderSub,
    TakeDamageWindSub,
    TakeDamagePhysicsGuardSuccessSub,
    TakeDamageMagicGuardSuccessSub,
    TakeDamageAttributeSub,
    TakeDamageSubAIPC,
    TakeDamageDebuffZeroProbability,
    TakeBuffTimeAdd = 80,
    GiveBuffTimeAdd,
    GiveDebuffTimeAdd,
    StatusChangeResistAdd,
    PoisonDamageSub,
    TakeDebuffTimeSub,
    MateriaIDEffect = 100,
    LimitLevelMaxFix_LimitValueSub,
    OnUseWeaponAbilityATBAdd,
    CombinationAbilityPowerAdd,
    OnGuardLimitAdd,
    OnBurstLimitAdd,
    OnBurstCreateDamageSource,
    ATBRecoverAdd = 110,
    MPRecoverTimeSub,
    LimitValueAdd,
    MPSpendAttackMagicSub,
    MPSpendHealMagicSub,
    MateriaSlotModify,
    HPRecoverKill,
    MPRecoverTakeDamage,
    WalkGetGill,
    CriticalWeaponAbilityAdd,
    HPRecoverBurstUniqueAbility,
    AppendAttributeDamageAdd,
    StartATBAdd,
    ItemDropAdd,
    SummonLevelAdd,
    ATBFullVision,
    LimitAddSpendATB,
    LimitAddSpendMP,
    StatusChangeAddBattleBegin,
    StatusChangeUnRemovedAddBattleBegin,
    StatusChangeUnRemovedAddSwitchableBattleBegin,
    LimitAddTime,
    UseAbility,
    AbilityStrengthenNumber,
    WorldItemCollectAdd,
    UseCombinationTypeCombinationAbility,
    MagicAbilityKeepAdd,
    StealSuccessRateAdd,
    AbilityMotionLoopTimeAdd,
    AbilityKeepAdd,
    OnCreateDamageSourceCreateDamageSource,
    DamageSourceHitBonusAdd,
    StealSuccessCreateDamageSource,
    AddAP,
    StoryFlagSet,
    OnJustGuardCreateDamageSource,
    LimitValueAddBattleBegin,
    UseAbilityVariationAddSpecialStatusChange,
    GiveDamageOffensiveModeCounterAdd = 150,
    GiveDamageOffensiveModeNormalAttackAdd,
    OffensiveModeDefenseAdd,
    TifaBuffAddBattleStart = 155,
    AddAttackTimeThrowWeapon,
    TimeEnergyAdd,
    ChargeEnergyAdd,
    OnBurstAddEnergy,
    SelfBuffTimeAdd,
    SelfBuffAttackBuffLevelAdd,
    OnReviveSelfBuffLevelAdd,
    AerithAssistTimeAdd,
    AerithWarpCoolDownTimeSub,
    SupportFieldTimeAdd,
    RevengeTimeAdd,
    RevengeModeRevengeTimeAdd,
    RevengeModeCreateDamageSource,
    OnReviveRevengeTimeAdd,
    GiveDamageRedXIIICounterAbilityAdd,
    FatMoogleGaugeLvBattleStart,
    FatMoogleRideLuckAdd,
    TakeDamageFatMoogleAdd,
    GiveDamageFatMoogleSub,
    FatMoogleTargetProbAdd,
};

