#pragma once
#include "CoreMinimal.h"
#include "EEndBattleSpecialStatusChangeType.generated.h"

UENUM(BlueprintType)
enum class EEndBattleSpecialStatusChangeType : uint8 {
    None,
    Barrier,
    SearchLaser,
    AIHands = 4,
    RocketPunch,
    CatchWithChain,
    CanNotAbility,
    CatchedByChain,
    SyncAction,
    Doping,
    LaunchByPhysics = 12,
    CatchWithChainDamageSource,
    ReactionDamageSource,
    DamageInvalid,
    LockOn,
    LockedOn,
    LocateDamageSource,
    CatchWithHandle,
    CatchedByHandle,
    WarpStyle,
    HideStyle,
    Appear,
    HitSlowAttack,
    BarretBuff,
    ControlEnvironmentActor,
    ReplaceEnvironmentActor,
    ThrowEnvironmentActor,
    TifaRiseBeat,
    CounterMode,
    ControlEnvironmentActorGroup,
    GhostStyle,
    BarretHPTransferBuff,
    BarretSpecialBullet,
    AerithAssist,
    PlayTouchEffect,
    PlayTouchEffectTargetIDGroup,
    PlayTouchEffectFeet,
    PlayBlendSpaceAction,
    OverwriteSyncAction,
    Bind,
    ApparentDeath,
    IceAura,
    SoulAbsorb,
    ThrowCharacter,
    ResetThrowCharacter,
    InRangeCheckDamage,
    SephirothWarpStyle,
    Vision,
    AttributeAssist,
    YuffieCalcDamageBuff,
    YuffieAttributeBuff,
    TitanProtection,
    OdinSeize,
    RamuhPowerUp,
    MPUnlimited,
    ElenaPunch,
    DroneCatcher,
    AerithStop,
    DisableRevival,
    SpecifyTargetStrafing,
    TimeAura,
    ThunderAura,
    CloneTechnique,
    IceReflect,
    CloneBody,
    CrimsonRocketPunch,
    BarretATBRegene,
    StonePillar,
    AerithSaintCharge,
    KickOff,
    MineMovement,
    StonePillarCollapse,
    AbilityLoopTimeManagement,
    BPDoT,
    OnDeadCreateDamageSource,
    HPMaxCoefficient,
    MPMaxCoefficient,
    TimePassesAddATB,
    MoveEnvironment,
    PullBindChara,
    CloudJenovaLifeJump,
    OverrideDeadMotionName,
    OdinStop,
    TimerEvent,
    GenjiShield,
    OneFrameStatusChange,
    PullIntoArea,
    CatchWithEffect,
    OnLandCreateDamageSource,
    SummonBuffTop = 220,
    SummonBuffRegene = SummonBuffTop,
    SummonBuffMaxHpBonus = 223,
    SummonBuffPhysicalAttackBonus,
    SummonBuffMagicAttackBonus,
    SummonBuffBottom,
    MAX,
};

