#include "EndAnimNotifyStateBattlePlayerKeyAssignAbilityOverrideCancelCondition.h"

FEndAnimNotifyStateBattlePlayerKeyAssignAbilityOverrideCancelCondition::FEndAnimNotifyStateBattlePlayerKeyAssignAbilityOverrideCancelCondition() {
    this->ConditionType = EEndAnimNotifyStateBattlePlayerKeyAssignAbilityOverrideCancelConditionType::None;
}

