#include "EndBattleDamageSourceExtensionComponentMagneticTornado.h"

UEndBattleDamageSourceExtensionComponentMagneticTornado::UEndBattleDamageSourceExtensionComponentMagneticTornado(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


