#include "EndBattleDamageSourceExtensionComponentCreateByPhysicsObjectHit.h"

UEndBattleDamageSourceExtensionComponentCreateByPhysicsObjectHit::UEndBattleDamageSourceExtensionComponentCreateByPhysicsObjectHit(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


