#include "EndBattleDamageSourceExtensionComponentTargetArrivalEnd.h"

UEndBattleDamageSourceExtensionComponentTargetArrivalEnd::UEndBattleDamageSourceExtensionComponentTargetArrivalEnd(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


