#include "EndBattleDamageSourceExtensionComponentDestroyOmenEmissive.h"

UEndBattleDamageSourceExtensionComponentDestroyOmenEmissive::UEndBattleDamageSourceExtensionComponentDestroyOmenEmissive(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


