#include "EndBattleDamageSourceExtensionComponentDestroyOmenEffect.h"

UEndBattleDamageSourceExtensionComponentDestroyOmenEffect::UEndBattleDamageSourceExtensionComponentDestroyOmenEffect(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


