#include "EndBattleDamageSourceExtensionComponentCheckPhysicsStable.h"

UEndBattleDamageSourceExtensionComponentCheckPhysicsStable::UEndBattleDamageSourceExtensionComponentCheckPhysicsStable(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


