#include "EndBattleDamageSourceExtensionComponentFollowOwnerPhysicsObject.h"

UEndBattleDamageSourceExtensionComponentFollowOwnerPhysicsObject::UEndBattleDamageSourceExtensionComponentFollowOwnerPhysicsObject(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


